# Generated by Django 3.2.4 on 2023-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosImportados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca_temporal', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('pregunta1', models.CharField(max_length=100)),
                ('pregunta2', models.CharField(max_length=100)),
                ('pregunta3', models.CharField(max_length=100)),
                ('pregunta4', models.CharField(max_length=100)),
                ('pregunta5', models.CharField(max_length=100)),
                ('pregunta6', models.CharField(max_length=100)),
                ('pregunta7', models.CharField(max_length=100)),
                ('pregunta8', models.CharField(max_length=100)),
                ('pregunta9', models.CharField(max_length=100)),
                ('pregunta10', models.CharField(max_length=100)),
            ],
        ),
    ]
