# Generated by Django 3.2.4 on 2023-10-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datosimportados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosImportados',
        ),
    ]
